---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mynso
  name: mynso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynso
  template:
    metadata:
      labels:
        app: mynso
    spec:
      containers:
      - image: 172.42.42.110:5000/v2:6
        imagePullPolicy: Always
        name: mynso
        command:
        - /bin/bash
        - -c
        - ncs

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynso
  name: mynso
spec:
  ports:
  - nodePort: 31001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mynso
  type: NodePort
